# Joins example sql select statement
SELECT 
    R.TITLE AS "Title",
    CONTRIBUTOR_AUTHOR.NAME AS "Author",
    p.LISTITEM as "Publisher",
    R.ISBN
FROM READERWARE R
LEFT JOIN CONTRIBUTOR AS CONTRIBUTOR_AUTHOR ON R.AUTHOR = CONTRIBUTOR_AUTHOR.ROWKEY
LEFT JOIN CONTRIBUTOR a on a.ROWKEY == r.AUTHOR
LEFT JOIN PUBLISHER_LIST p ON r.PUBLISHER = p.ROWKEY